package com.yt.sportservice.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yt.sportservice.entity.StepHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP_HISTORY".
*/
public class StepHistoryDao extends AbstractDao<StepHistory, Long> {

    public static final String TABLENAME = "STEP_HISTORY";

    /**
     * Properties of entity StepHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Imei = new Property(1, String.class, "imei", false, "IMEI");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property StepTime = new Property(3, String.class, "stepTime", false, "STEP_TIME");
        public final static Property Step_count = new Property(4, long.class, "step_count", false, "STEP_COUNT");
        public final static Property Limit = new Property(5, long.class, "limit", false, "LIMIT");
        public final static Property Step_energy = new Property(6, long.class, "step_energy", false, "STEP_ENERGY");
        public final static Property Time = new Property(7, long.class, "time", false, "TIME");
    }


    public StepHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public StepHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP_HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"IMEI\" TEXT," + // 1: imei
                "\"DATE\" TEXT," + // 2: date
                "\"STEP_TIME\" TEXT," + // 3: stepTime
                "\"STEP_COUNT\" INTEGER NOT NULL ," + // 4: step_count
                "\"LIMIT\" INTEGER NOT NULL ," + // 5: limit
                "\"STEP_ENERGY\" INTEGER NOT NULL ," + // 6: step_energy
                "\"TIME\" INTEGER NOT NULL );"); // 7: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StepHistory entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String imei = entity.getImei();
        if (imei != null) {
            stmt.bindString(2, imei);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String stepTime = entity.getStepTime();
        if (stepTime != null) {
            stmt.bindString(4, stepTime);
        }
        stmt.bindLong(5, entity.getStep_count());
        stmt.bindLong(6, entity.getLimit());
        stmt.bindLong(7, entity.getStep_energy());
        stmt.bindLong(8, entity.getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StepHistory entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String imei = entity.getImei();
        if (imei != null) {
            stmt.bindString(2, imei);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String stepTime = entity.getStepTime();
        if (stepTime != null) {
            stmt.bindString(4, stepTime);
        }
        stmt.bindLong(5, entity.getStep_count());
        stmt.bindLong(6, entity.getLimit());
        stmt.bindLong(7, entity.getStep_energy());
        stmt.bindLong(8, entity.getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public StepHistory readEntity(Cursor cursor, int offset) {
        StepHistory entity = new StepHistory( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imei
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // stepTime
            cursor.getLong(offset + 4), // step_count
            cursor.getLong(offset + 5), // limit
            cursor.getLong(offset + 6), // step_energy
            cursor.getLong(offset + 7) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StepHistory entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setImei(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStepTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStep_count(cursor.getLong(offset + 4));
        entity.setLimit(cursor.getLong(offset + 5));
        entity.setStep_energy(cursor.getLong(offset + 6));
        entity.setTime(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StepHistory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StepHistory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StepHistory entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
